# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: security-check

on:
  push:
    branches: [ "master" ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "master" ]

jobs:
  security-check:
    name: Security checks
    container: nirahsab/hub-cli:1.9
    runs-on: ubuntu-latest
    steps:
      - name: Run AppSec.Hub CLI
        run: |
          ls -al /opt/scan
        shell: bash
